# base image for init database
FROM circleci/node:13.8.0
USER root
# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH


COPY . /usr/src/app/

RUN chown root:root /usr/src/app && \
    mkdir /.npm && chown root:root /.npm && \
    mkdir /.config && chown root:root /.config && \
    mkdir /.cache && chown root:root /.cache && \
    mkdir /.local && chown root:root /.local

USER root

RUN npm install

# start init database
CMD ["npm", "run", "build"]