# docker-compose.yml
version: "3"
services:
#  database:
#    image: "postgres"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=glee
#    ports:
#      - "5432:5432"
#    networks:
#      - "backend"
  backend:
    build: ./backend
    ports:
      - "3030:3030"
    image: huannv93/udacity-awsdevops-project03-1_backend #naming for image when docker-compose build
    networks:
      - "backend"
#    depends_on:
#      - "database"
#  backend-db:
#    build: ./backend-db
#    networks:
#      - "backend"
#    depends_on:
#      - "database"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - "backend"
    depends_on:
      - "backend"
    image: huannv93/udacity-awsdevops-project03-1_frontend ##naming for image when docker-compose build
#      - "database"
networks:
  backend:


